monitorInterval = 300

appender.0.type = Console
appender.0.name = CONSOLE
appender.0.layout.type = PatternLayout
appender.0.layout.pattern = %d [%t] %p %c - %m%n

appender.1.type = File
appender.1.name = WANDORA_LOG
appender.1.fileName = logs/wandora.log
appender.1.layout.type = PatternLayout
appender.1.layout.pattern = %d [%t] %p %c - %m%n

rootLogger.level = INFO
rootLogger.appenderRef.0.ref = CONSOLE
rootLogger.appenderRef.0.level = INFO

logger.0.name = org.wandora
logger.0.level = DEBUG
logger.0.appenderRef.0.ref = WANDORA_LOG