/*
 * WANDORA
 * Knowledge Extraction, Management, and Publishing Application
 * http://wandora.org
 *
 * Copyright (C) 2004-2015 Wandora Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * MicrosoftTranslateConfiguration.java
 *
 * Created on 1.6.2011, 15:32:04
 */


package org.wandora.utils.language;

import javax.swing.JDialog;
import org.wandora.application.Wandora;
import org.wandora.application.gui.UIBox;
import org.wandora.application.gui.simple.SimpleButton;
import org.wandora.application.gui.simple.SimpleLabel;

/**
 *
 * @author akivela
 */
public class MicrosoftTranslateConfiguration extends javax.swing.JPanel {

    private JDialog myDialog = null;


    /** Creates new form MicrosoftTranslateConfiguration */
    public MicrosoftTranslateConfiguration() {
        initComponents();
    }



    public void open(Wandora w) {
        myDialog = new JDialog(w, true);
        myDialog.add(this);
        myDialog.setSize(350, 220);
        myDialog.setTitle("Configure Microsoft Translator");
        UIBox.centerWindow(myDialog, w);
        myDialog.setVisible(true);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        forgetPanel = new javax.swing.JPanel();
        forgetLabel = new SimpleLabel();
        forgetButton = new SimpleButton();
        buttonPanel = new javax.swing.JPanel();
        buttonPanelFiller = new javax.swing.JPanel();
        okButton = new SimpleButton();

        setLayout(new java.awt.GridBagLayout());

        forgetPanel.setLayout(new java.awt.GridBagLayout());

        forgetLabel.setText("<html>This dialog is used to clear Wandora's Bing API Key used to access Microsoft Translator Service. To clear the key, press Forget API Key button below. Once the key is cleared, Wandora requests API Key again when you start the translator tool.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        forgetPanel.add(forgetLabel, gridBagConstraints);

        forgetButton.setText("Forget API Key");
        forgetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgetButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        forgetPanel.add(forgetButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(forgetPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        buttonPanelFiller.setPreferredSize(new java.awt.Dimension(265, 10));

        javax.swing.GroupLayout buttonPanelFillerLayout = new javax.swing.GroupLayout(buttonPanelFiller);
        buttonPanelFiller.setLayout(buttonPanelFillerLayout);
        buttonPanelFillerLayout.setHorizontalGroup(
            buttonPanelFillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        buttonPanelFillerLayout.setVerticalGroup(
            buttonPanelFillerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        buttonPanel.add(buttonPanelFiller, gridBagConstraints);

        okButton.setText("Close");
        okButton.setMinimumSize(new java.awt.Dimension(70, 23));
        okButton.setPreferredSize(new java.awt.Dimension(70, 23));
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButtonMouseReleased(evt);
            }
        });
        buttonPanel.add(okButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 8);
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void forgetButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetButtonMouseReleased
        MicrosoftTranslateBox.resetAPIKey();
    }//GEN-LAST:event_forgetButtonMouseReleased

    private void okButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseReleased
        if(myDialog != null) myDialog.setVisible(false);
    }//GEN-LAST:event_okButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel buttonPanelFiller;
    private javax.swing.JButton forgetButton;
    private javax.swing.JLabel forgetLabel;
    private javax.swing.JPanel forgetPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
