/*
 * WANDORA
 * Knowledge Extraction, Management, and Publishing Application
 * http://wandora.org
 *
 * Copyright (C) 2004-2016 Wandora Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 
 *
 */




package org.wandora.utils.language;


import javax.swing.JDialog;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import org.wandora.application.Wandora;
import org.wandora.application.gui.simple.SimpleButton;
import org.wandora.application.gui.simple.SimpleCheckBox;
import org.wandora.application.gui.simple.SimpleLabel;


/**
 *
 * @author akivela
 */
public class SelectWatsonTranslationLanguagesPanel extends javax.swing.JPanel {
    private static String selectedLanguages = null;
    
    private static String[] languages = null;

    private boolean accepted = false;
    private JDialog dialog = null;



    /** Creates new form SelectWatsonTranslationLanguagesPanel */
    public SelectWatsonTranslationLanguagesPanel() {
        initComponents();
    }


    public void openInDialog(Wandora wandora) {
        setLanguages();

        accepted = false;

        dialog = new JDialog(wandora, true);
        dialog.setSize(500,350);
        dialog.setTitle("Select translation languages");
        wandora.centerWindow(dialog);
        dialog.add(this);
        dialog.setVisible(true);
    }


    
    public void notInTopicMapsContext() {
        overrideCheckBox.setVisible(false);
        createTopicsCheckBox.setVisible(false);
    }


    private void setLanguages() {
        languages = WatsonTranslateBox.getAvailableTranslations();
        languagesList.setModel(new LanguageListModel(languages));
        if(selectedLanguages != null) languagesList.setSelectedValue(selectedLanguages, true);
    }


    public boolean wasAccepted() {
        return accepted;
    }
    public boolean overrideExisting() {
        return overrideCheckBox.isSelected();
    }
    public boolean createTopics() {
        return createTopicsCheckBox.isSelected();
    }
    public boolean markTranslatedText() {
        return markTranslationCheckBox.isSelected();
    }

    

    public String getSelectedLanguages() {
        int i = languagesList.getSelectedIndex();
        selectedLanguages = languages[i];
        return selectedLanguages;
    }




    /* ---------------------------------------------------------------------- */
    /* ---------------------------------------------------------------------- */



    private class LanguageListModel implements ListModel {
        String[] model = null;


        public LanguageListModel(String[] m) {
            model = m;
        }


        @Override
        public int getSize() {
            return model.length;
        }

        @Override
        public Object getElementAt(int index) {
            String lan = model[index];
            return lan;
        }

        @Override
        public void addListDataListener(ListDataListener l) {

        }

        @Override
        public void removeListDataListener(ListDataListener l) {

        }

    }




    /* ---------------------------------------------------------------------- */
    /* ---------------------------------------------------------------------- */
    /* ---------------------------------------------------------------------- */

    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        innerPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        infoLabel = new SimpleLabel();
        sourceScrollPane = new javax.swing.JScrollPane();
        languagesList = new javax.swing.JList();
        overrideCheckBox = new SimpleCheckBox();
        createTopicsCheckBox = new SimpleCheckBox();
        markTranslationCheckBox = new SimpleCheckBox();
        buttonPanel = new javax.swing.JPanel();
        fillerPanel = new javax.swing.JPanel();
        translateButton = new SimpleButton();
        cancelButton = new SimpleButton();

        setLayout(new java.awt.GridBagLayout());

        innerPanel.setLayout(new java.awt.GridBagLayout());

        contentPanel.setLayout(new java.awt.GridBagLayout());

        infoLabel.setText("<html>Select translation languages. Checking Mark translated text adds translated a static suffix helping to recognize and verify the translated texts.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        contentPanel.add(infoLabel, gridBagConstraints);

        sourceScrollPane.setMinimumSize(new java.awt.Dimension(100, 100));
        sourceScrollPane.setPreferredSize(new java.awt.Dimension(100, 100));

        languagesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        languagesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        sourceScrollPane.setViewportView(languagesList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        contentPanel.add(sourceScrollPane, gridBagConstraints);

        overrideCheckBox.setSelected(true);
        overrideCheckBox.setText("Override existing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        contentPanel.add(overrideCheckBox, gridBagConstraints);

        createTopicsCheckBox.setText("Create necessary topics");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        contentPanel.add(createTopicsCheckBox, gridBagConstraints);

        markTranslationCheckBox.setSelected(true);
        markTranslationCheckBox.setText("Mark translated text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        contentPanel.add(markTranslationCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        innerPanel.add(contentPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout fillerPanelLayout = new javax.swing.GroupLayout(fillerPanel);
        fillerPanel.setLayout(fillerPanelLayout);
        fillerPanelLayout.setHorizontalGroup(
            fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fillerPanelLayout.setVerticalGroup(
            fillerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        buttonPanel.add(fillerPanel, gridBagConstraints);

        translateButton.setText("Continue");
        translateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                translateButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        buttonPanel.add(translateButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });
        buttonPanel.add(cancelButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 2, 0);
        innerPanel.add(buttonPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(innerPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void translateButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_translateButtonMouseReleased
        accepted = true;
        if(dialog != null) dialog.setVisible(false);
    }//GEN-LAST:event_translateButtonMouseReleased

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        accepted = false;
        if(dialog != null) dialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JCheckBox createTopicsCheckBox;
    private javax.swing.JPanel fillerPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JList languagesList;
    private javax.swing.JCheckBox markTranslationCheckBox;
    private javax.swing.JCheckBox overrideCheckBox;
    private javax.swing.JScrollPane sourceScrollPane;
    private javax.swing.JButton translateButton;
    // End of variables declaration//GEN-END:variables

}
