/*
 * WANDORA
 * Knowledge Extraction, Management, and Publishing Application
 * http://wandora.org
 *
 * Copyright (C) 2004-2014 Wandora Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 
 * VariantNameEditor.java
 *
 * Created on 26.4.2011, 17:53:33
 */



package org.wandora.application.gui;


import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.ListModel;
import org.wandora.application.Wandora;
import org.wandora.application.gui.simple.*;
import org.wandora.topicmap.Locator;
import org.wandora.topicmap.Topic;
import org.wandora.topicmap.TopicMap;
import org.wandora.topicmap.TopicMapException;


/**
 *
 * @author akivela
 */
public class VariantNameEditor extends javax.swing.JPanel {

    private JDialog myDialog = null;
    private boolean wasAccepted = false;
    private ArrayList<Topic> scopeTopics = new ArrayList<Topic>();
    private Wandora wandora = null;
    private static ArrayList<Locator> lastScopeSubjects = new ArrayList<Locator>();


    /** Creates new form VariantNameEditor */
    public VariantNameEditor(Wandora w) {
        wandora = w;
        initComponents();
    }

    
    public void initialize(Set<Topic> scope, String variantString) {
        if(variantString != null) variantTextField.setText(variantString);
        else variantTextField.setText("");
        scopeTopics.addAll(scope);
        wasAccepted = false;
    }


    public void openEditor(String title) {
        wandora = Wandora.getWandora();
        
        myDialog = new JDialog(wandora, true);
        myDialog.add(this);
        myDialog.setSize(500,300);
        myDialog.setTitle(title);
        wandora.centerWindow(myDialog);

        myDialog.setVisible(true);
    }


    // -----


    public boolean wasAccepted() {
        return wasAccepted;
    }

    public String getVariantString() {
        return variantTextField.getText();
    }

    public Set<Topic> getVariantScope() {
        LinkedHashSet<Topic> set =  new LinkedHashSet();
        set.addAll(scopeTopics);
        return set;
    }





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        innerPanel = new javax.swing.JPanel();
        nameLabel = new SimpleLabel();
        variantTextField = new SimpleField();
        scopeLabel = new SimpleLabel();
        scopeTopicScrollPane = new SimpleScrollPane();
        scopeTopicList = new javax.swing.JList();
        scopeButtonPanel = new javax.swing.JPanel();
        addScopeTopicButton = new SimpleButton();
        removeScopeTopicButton = new SimpleButton();
        addSameAsPreviousButton = new SimpleButton();
        buttonPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        okButton = new SimpleButton();
        cancelButton = new SimpleButton();

        setLayout(new java.awt.GridBagLayout());

        innerPanel.setLayout(new java.awt.GridBagLayout());

        nameLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 4);
        innerPanel.add(nameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        innerPanel.add(variantTextField, gridBagConstraints);

        scopeLabel.setText("Scope");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        innerPanel.add(scopeLabel, gridBagConstraints);

        scopeTopicScrollPane.setMinimumSize(new java.awt.Dimension(23, 130));

        scopeTopicList.setModel(new VariantScopeListModel());
        scopeTopicScrollPane.setViewportView(scopeTopicList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        innerPanel.add(scopeTopicScrollPane, gridBagConstraints);

        scopeButtonPanel.setLayout(new java.awt.GridBagLayout());

        addScopeTopicButton.setText("Add scope topic");
        addScopeTopicButton.setMargin(new java.awt.Insets(0, 6, 0, 6));
        addScopeTopicButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addScopeTopicButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        scopeButtonPanel.add(addScopeTopicButton, gridBagConstraints);

        removeScopeTopicButton.setText("Remove scope topic(s)");
        removeScopeTopicButton.setMargin(new java.awt.Insets(0, 6, 0, 6));
        removeScopeTopicButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                removeScopeTopicButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        scopeButtonPanel.add(removeScopeTopicButton, gridBagConstraints);

        addSameAsPreviousButton.setText("Add same scope topics");
        addSameAsPreviousButton.setMargin(new java.awt.Insets(0, 6, 0, 6));
        addSameAsPreviousButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                addSameAsPreviousButtonMouseReleased(evt);
            }
        });
        scopeButtonPanel.add(addSameAsPreviousButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        innerPanel.add(scopeButtonPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(innerPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        buttonPanel.add(jPanel3, gridBagConstraints);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(70, 23));
        okButton.setMinimumSize(new java.awt.Dimension(70, 23));
        okButton.setPreferredSize(new java.awt.Dimension(70, 23));
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                okButtonMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        buttonPanel.add(okButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(70, 23));
        cancelButton.setMinimumSize(new java.awt.Dimension(70, 23));
        cancelButton.setPreferredSize(new java.awt.Dimension(70, 23));
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cancelButtonMouseReleased(evt);
            }
        });
        buttonPanel.add(cancelButton, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(buttonPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseReleased
        wasAccepted = false;
        if(myDialog != null) myDialog.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseReleased

    private void okButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseReleased
        if(scopeTopics != null && !scopeTopics.isEmpty()) {
            lastScopeSubjects = new ArrayList<Locator>();
            for(Topic t : scopeTopics) {
                try {
                    if(t != null && !t.isRemoved()) {
                        lastScopeSubjects.add(t.getOneSubjectIdentifier());
                    }
                } 
                catch (TopicMapException ex) {
                    Logger.getLogger(VariantNameEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        wasAccepted = true;
        if(myDialog != null) myDialog.setVisible(false);
    }//GEN-LAST:event_okButtonMouseReleased

    private void addScopeTopicButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addScopeTopicButtonMouseReleased
        try {
            Topic addedScope = wandora.showTopicFinder("Select variant scope topic...");
            if(addedScope != null) {
                scopeTopics.add(addedScope);
                scopeTopicList.setModel(new VariantScopeListModel());
            }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addScopeTopicButtonMouseReleased



    private void removeScopeTopicButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeScopeTopicButtonMouseReleased
        try {
            int[] selection = scopeTopicList.getSelectedIndices();
            ArrayList<Topic> removeScopeTopics = new ArrayList();
            for(int i=0; i<selection.length; i++) {
                removeScopeTopics.add(scopeTopics.get(selection[i]));
            }
            scopeTopics.removeAll(removeScopeTopics);
            scopeTopicList.setModel(new VariantScopeListModel());
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_removeScopeTopicButtonMouseReleased

    private void addSameAsPreviousButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addSameAsPreviousButtonMouseReleased
        if(lastScopeSubjects != null && !lastScopeSubjects.isEmpty()) {
            TopicMap tm = Wandora.getWandora().getTopicMap();
            Topic t;
            for(Locator l : lastScopeSubjects) {
                try {
                    t = tm.getTopic(l);
                    if(t != null && !t.isRemoved()) {
                        scopeTopics.add(t);
                    }
                } 
                catch (TopicMapException ex) {
                    Logger.getLogger(VariantNameEditor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            scopeTopicList.setModel(new VariantScopeListModel());
        }
    }//GEN-LAST:event_addSameAsPreviousButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSameAsPreviousButton;
    private javax.swing.JButton addScopeTopicButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel innerPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeScopeTopicButton;
    private javax.swing.JPanel scopeButtonPanel;
    private javax.swing.JLabel scopeLabel;
    private javax.swing.JList scopeTopicList;
    private javax.swing.JScrollPane scopeTopicScrollPane;
    private javax.swing.JTextField variantTextField;
    // End of variables declaration//GEN-END:variables





    private class VariantScopeListModel extends DefaultListModel implements ListModel {

        @Override
        public int getSize() {
            if(scopeTopics != null) {
                return scopeTopics.size();
            }
            else {
                return 0;
            }
        }

        
        @Override
        public Object getElementAt(int index) {
            if(scopeTopics != null) {
                if(index >= 0 && index < scopeTopics.size()) {
                    return scopeTopics.get(index);
                }
            }
            return null;
        }

    }





}
